### ISSUE TITLE
Updating preventSwipe prop after initial render does not take effect

### ISSUE THREAD

**Issue by benkaiser** [3DJakob/react-tinder-card#30]
Only the preventSwipe prop passed on initial render of a tinder card is taken into account. If you proceed to update the prop later with a new set of prevented directions, they will not take effect.

I'm not that great with hook components in React. I tried adding [preventSwipe] to the deps of the React.useLayoutEffect but it didn't seem to fix the behavior.

**Comment by benkaiser** [comment]
Fixed in this PR: https://github.com/3DJakob/react-tinder-card/pull/31

**Comment by 3DJakob** [comment]
Great addition, good catch! I will take a look at your PR and merge it asap!

**Comment by shubhurwt2001** [comment]
Hi, I'm still not able to fix this issue. Can someone help? I'm working with react-tinder-card 1.5.4
